#This is the name of the workflow taht will be displayed in the Action Tab
name: CICD

on:
  workflow_dispatch: 
    inputs: 
      enviornment:
        description: 'This is the enviornment value where workflows runs' 
        default: 'dev'
        required: true
        type: choice
        options: 
          - dev
          - pord
          - stagings

jobs:
  
   code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          run: echo "Code cloned from GitHub"
          
   build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
        - name: build docker container
          run: echo "docker container build"

   Test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: Test the container"
          run: echo "Testing the container"
          
   deploy:
      needs: [build, Test]
      runs-on: ubuntu-latest
      steps:
        - name: Deploying the Container 
          run: echo "Docker compose deployed the app"
